# Blocks CPack so a developer can't accidentally produce a broken installer from
# a single build tree. A correct shipping artifact merges multiple (platform,
# config) trees and is built by scripts/package.py; any single tree holds one
# config, so cpack against it is always subtly wrong.
#
# Not calling include(CPack) already kills the `--target package` vector (those
# targets don't exist without it). What remains is the `cpack` binary run
# directly in a build tree: it reads CPackConfig.cmake / CPackSourceConfig.cmake
# as CMake scripts, so we write our own copies that abort with FATAL_ERROR.
#
# Call adhoc_block_cpack() once from the top-level CMakeLists after project().
function(adhoc_block_cpack)
    set(_blocked_script "${CMAKE_BINARY_DIR}/adhoc-cpack-blocked.cmake")
    set(_message
"\n\
CPack is disabled for AdHocEngine.\
\n\
A single build tree cannot produce a correct installer: the shipping artifact \
merges Debug + Release (and cross-compiled) trees, embeds the LLVM toolchain, \
and codesigns / runs the installer step over the merged layout.\
\n\
Run instead:  python scripts/package.py\
\n")

    # Shared abort script, invoked by both the cpack configs and the build targets.
    file(WRITE "${_blocked_script}" "message(FATAL_ERROR \"${_message}\")\n")

    # cpack reads these from the build dir and runs them as CMake scripts, so
    # FATAL_ERROR here aborts cpack with our message.
    set(_cpack_config
"# Generated by AdHocEngine (cmake/AdHocBlockCPack.cmake) — do not edit.\n\
# AdHocEngine intentionally does not include(CPack); see scripts/package.py.\n\
include(\"${_blocked_script}\")\n")
    file(WRITE "${CMAKE_BINARY_DIR}/CPackConfig.cmake"       "${_cpack_config}")
    file(WRITE "${CMAKE_BINARY_DIR}/CPackSourceConfig.cmake" "${_cpack_config}")
endfunction()
